"""add_multi_tenant_schema

Revision ID: 133309f277b9
Revises: 
Create Date: 2025-12-15 14:37:10.880088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '133309f277b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('business_type', sa.String(length=50), nullable=True),
    sa.Column('cuisine_type', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.String(length=20), nullable=True),
    sa.Column('longitude', sa.String(length=20), nullable=True),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('banner_image', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('date_format', sa.String(length=20), nullable=True),
    sa.Column('time_format', sa.String(length=10), nullable=True),
    sa.Column('subscription_plan', sa.String(length=50), nullable=True),
    sa.Column('subscription_status', sa.String(length=20), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('billing_email', sa.String(length=255), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_products', sa.Integer(), nullable=True),
    sa.Column('max_orders_per_month', sa.Integer(), nullable=True),
    sa.Column('max_locations', sa.Integer(), nullable=True),
    sa.Column('current_users', sa.Integer(), nullable=True),
    sa.Column('current_products', sa.Integer(), nullable=True),
    sa.Column('current_orders_this_month', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('suspension_reason', sa.Text(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('onboarding_step', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurants_created_at'), 'restaurants', ['created_at'], unique=False)
    op.create_index(op.f('ix_restaurants_email'), 'restaurants', ['email'], unique=False)
    op.create_index(op.f('ix_restaurants_is_active'), 'restaurants', ['is_active'], unique=False)
    op.create_index(op.f('ix_restaurants_name'), 'restaurants', ['name'], unique=False)
    op.create_index(op.f('ix_restaurants_slug'), 'restaurants', ['slug'], unique=True)
    op.create_index(op.f('ix_restaurants_subscription_plan'), 'restaurants', ['subscription_plan'], unique=False)
    op.create_index(op.f('ix_restaurants_subscription_status'), 'restaurants', ['subscription_status'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tagline', sa.String(length=200), nullable=True),
    sa.Column('price_monthly', sa.Integer(), nullable=True),
    sa.Column('price_yearly', sa.Integer(), nullable=True),
    sa.Column('discount_yearly', sa.Integer(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_products', sa.Integer(), nullable=True),
    sa.Column('max_orders_per_month', sa.Integer(), nullable=True),
    sa.Column('max_locations', sa.Integer(), nullable=True),
    sa.Column('max_storage_gb', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('badge', sa.String(length=50), nullable=True),
    sa.Column('trial_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_name'), 'subscription_plans', ['name'], unique=True)
    op.create_table('platform_admins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('can_access_all_restaurants', sa.Boolean(), nullable=True),
    sa.Column('can_modify_subscriptions', sa.Boolean(), nullable=True),
    sa.Column('can_suspend_restaurants', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_admins_user_id'), 'platform_admins', ['user_id'], unique=True)
    op.create_table('restaurant_invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_invitations_email'), 'restaurant_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_restaurant_invitations_restaurant_id'), 'restaurant_invitations', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_restaurant_invitations_token'), 'restaurant_invitations', ['token'], unique=True)
    op.create_table('restaurant_owners',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('invited_by', sa.String(length=36), nullable=True),
    sa.Column('invitation_accepted', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_owners_restaurant_id'), 'restaurant_owners', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_restaurant_owners_user_id'), 'restaurant_owners', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('price_per_month', sa.Integer(), nullable=True),
    sa.Column('price_per_year', sa.Integer(), nullable=True),
    sa.Column('billing_cycle', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_gateway_customer_id', sa.String(length=255), nullable=True),
    sa.Column('payment_gateway_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('last_payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_by', sa.String(length=36), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_payment_gateway_subscription_id'), 'subscriptions', ['payment_gateway_subscription_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_plan'), 'subscriptions', ['plan'], unique=False)
    op.create_index(op.f('ix_subscriptions_restaurant_id'), 'subscriptions', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('tax', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invoice_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_gateway_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('payment_gateway_charge_id', sa.String(length=255), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_restaurant_id'), 'invoices', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_invoices_subscription_id'), 'invoices', ['subscription_id'], unique=False)
    op.drop_index('idx_entity_lookup', table_name='translations')
    op.drop_index('idx_language', table_name='translations')
    op.drop_index('idx_unique_translation', table_name='translations')
    op.drop_table('translations')
    op.add_column('categories', sa.Column('restaurant_id', sa.String(length=36), nullable=False))
    op.alter_column('categories', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('categories', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('ix_categories_name', table_name='categories')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.drop_index('ix_categories_slug', table_name='categories')
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=False)
    op.create_index(op.f('ix_categories_restaurant_id'), 'categories', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'categories', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('combo_items', sa.Column('restaurant_id', sa.String(length=36), nullable=False))
    op.alter_column('combo_items', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_combo_items_restaurant_id'), 'combo_items', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'combo_items', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('combo_products', sa.Column('restaurant_id', sa.String(length=36), nullable=False))
    op.alter_column('combo_products', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('combo_products', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('ix_combo_products_slug', table_name='combo_products')
    op.create_index(op.f('ix_combo_products_slug'), 'combo_products', ['slug'], unique=False)
    op.create_index(op.f('ix_combo_products_restaurant_id'), 'combo_products', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'combo_products', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('customer_tag_mapping', sa.Column('restaurant_id', sa.String(length=36), nullable=False))
    op.alter_column('customer_tag_mapping', 'assigned_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_customer_tag_mapping_restaurant_id'), 'customer_tag_mapping', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'customer_tag_mapping', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('customer_tags', sa.Column('restaurant_id', sa.String(length=36), nullable=False))
    op.alter_column('customer_tags', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('customer_tags', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('ix_customer_tags_name', table_name='customer_tags')
    op.create_index(op.f('ix_customer_tags_name'), 'customer_tags', ['name'], unique=False)
    op.create_index(op.f('ix_customer_tags_restaurant_id'), 'customer_tags', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'customer_tags', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('customers', sa.Column('restaurant_id', sa.String(length=36), nullable=False))
    op.alter_column('customers', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('customers', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('email', table_name='customers')
    op.drop_index('ix_customers_phone', table_name='customers')
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_index(op.f('ix_customers_restaurant_id'), 'customers', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'customers', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('kot_groups', sa.Column('restaurant_id', sa.String(length=36), nullable=False))
    op.alter_column('kot_groups', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('kot_groups', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_kot_groups_restaurant_id'), 'kot_groups', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'kot_groups', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('loyalty_rules', sa.Column('restaurant_id', sa.String(length=36), nullable=False))
    op.alter_column('loyalty_rules', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('loyalty_rules', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_loyalty_rules_restaurant_id'), 'loyalty_rules', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'loyalty_rules', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('loyalty_transactions', sa.Column('restaurant_id', sa.String(length=36), nullable=False))
    op.alter_column('loyalty_transactions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_loyalty_transactions_restaurant_id'), 'loyalty_transactions', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'loyalty_transactions', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('modifier_options', sa.Column('restaurant_id', sa.String(length=36), nullable=False))
    op.alter_column('modifier_options', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('modifier_options', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_modifier_options_restaurant_id'), 'modifier_options', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'modifier_options', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('modifiers', sa.Column('restaurant_id', sa.String(length=36), nullable=False))
    op.alter_column('modifiers', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('modifiers', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_modifiers_restaurant_id'), 'modifiers', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'modifiers', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('order_item_modifiers', sa.Column('restaurant_id', sa.String(length=36), nullable=False))
    op.alter_column('order_item_modifiers', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_order_item_modifiers_restaurant_id'), 'order_item_modifiers', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'order_item_modifiers', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('order_items', sa.Column('restaurant_id', sa.String(length=36), nullable=False))
    op.alter_column('order_items', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('order_items', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_order_items_restaurant_id'), 'order_items', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'order_items', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('order_status_history', sa.Column('restaurant_id', sa.String(length=36), nullable=False))
    op.alter_column('order_status_history', 'timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_order_status_history_restaurant_id'), 'order_status_history', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'order_status_history', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('order_taxes', sa.Column('restaurant_id', sa.String(length=36), nullable=False))
    op.alter_column('order_taxes', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_order_taxes_restaurant_id'), 'order_taxes', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'order_taxes', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('orders', sa.Column('restaurant_id', sa.String(length=36), nullable=False))
    op.alter_column('orders', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('orders', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('ix_orders_order_number', table_name='orders')
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=False)
    op.create_index(op.f('ix_orders_restaurant_id'), 'orders', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.add_column('product_modifiers', sa.Column('restaurant_id', sa.String(length=36), nullable=False))
    op.alter_column('product_modifiers', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_product_modifiers_restaurant_id'), 'product_modifiers', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'product_modifiers', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('products', sa.Column('restaurant_id', sa.String(length=36), nullable=False))
    op.alter_column('products', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('products', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('ix_products_slug', table_name='products')
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=False)
    op.create_index(op.f('ix_products_restaurant_id'), 'products', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'products', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('qr_sessions', sa.Column('restaurant_id', sa.String(length=36), nullable=False))
    op.alter_column('qr_sessions', 'start_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('qr_sessions', 'last_activity',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('qr_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_qr_sessions_restaurant_id'), 'qr_sessions', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'qr_sessions', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('qr_settings', sa.Column('restaurant_id', sa.String(length=36), nullable=False))
    op.alter_column('qr_settings', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_qr_settings_restaurant_id'), 'qr_settings', ['restaurant_id'], unique=True)
    op.create_foreign_key(None, 'qr_settings', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('qr_tables', sa.Column('restaurant_id', sa.String(length=36), nullable=False))
    op.alter_column('qr_tables', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('qr_tables', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('ix_qr_tables_qr_token', table_name='qr_tables')
    op.create_index(op.f('ix_qr_tables_qr_token'), 'qr_tables', ['qr_token'], unique=False)
    op.drop_index('ix_qr_tables_table_number', table_name='qr_tables')
    op.create_index(op.f('ix_qr_tables_table_number'), 'qr_tables', ['table_number'], unique=False)
    op.create_index(op.f('ix_qr_tables_restaurant_id'), 'qr_tables', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'qr_tables', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('settings', sa.Column('restaurant_id', sa.String(length=36), nullable=False))
    op.alter_column('settings', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_settings_restaurant_id'), 'settings', ['restaurant_id'], unique=True)
    op.create_foreign_key(None, 'settings', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('shift_schedules', sa.Column('restaurant_id', sa.String(length=36), nullable=False))
    op.alter_column('shift_schedules', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('shift_schedules', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_shift_schedules_restaurant_id'), 'shift_schedules', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'shift_schedules', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('staff_performance', sa.Column('restaurant_id', sa.String(length=36), nullable=False))
    op.alter_column('staff_performance', 'last_calculated',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('staff_performance', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('staff_performance', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_staff_performance_restaurant_id'), 'staff_performance', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'staff_performance', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('tax_rules', sa.Column('restaurant_id', sa.String(length=36), nullable=False))
    op.alter_column('tax_rules', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('tax_rules', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_tax_rules_restaurant_id'), 'tax_rules', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'tax_rules', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('restaurant_id', sa.String(length=36), nullable=True))
    op.alter_column('users', 'join_date',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_users_restaurant_id'), 'users', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'users', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_restaurant_id'), table_name='users')
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('users', 'join_date',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('users', 'restaurant_id')
    op.drop_constraint(None, 'tax_rules', type_='foreignkey')
    op.drop_index(op.f('ix_tax_rules_restaurant_id'), table_name='tax_rules')
    op.alter_column('tax_rules', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('tax_rules', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('tax_rules', 'restaurant_id')
    op.drop_constraint(None, 'staff_performance', type_='foreignkey')
    op.drop_index(op.f('ix_staff_performance_restaurant_id'), table_name='staff_performance')
    op.alter_column('staff_performance', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('staff_performance', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('staff_performance', 'last_calculated',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('staff_performance', 'restaurant_id')
    op.drop_constraint(None, 'shift_schedules', type_='foreignkey')
    op.drop_index(op.f('ix_shift_schedules_restaurant_id'), table_name='shift_schedules')
    op.alter_column('shift_schedules', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('shift_schedules', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('shift_schedules', 'restaurant_id')
    op.drop_constraint(None, 'settings', type_='foreignkey')
    op.drop_index(op.f('ix_settings_restaurant_id'), table_name='settings')
    op.alter_column('settings', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('settings', 'restaurant_id')
    op.drop_constraint(None, 'qr_tables', type_='foreignkey')
    op.drop_index(op.f('ix_qr_tables_restaurant_id'), table_name='qr_tables')
    op.drop_index(op.f('ix_qr_tables_table_number'), table_name='qr_tables')
    op.create_index('ix_qr_tables_table_number', 'qr_tables', ['table_number'], unique=True)
    op.drop_index(op.f('ix_qr_tables_qr_token'), table_name='qr_tables')
    op.create_index('ix_qr_tables_qr_token', 'qr_tables', ['qr_token'], unique=True)
    op.alter_column('qr_tables', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('qr_tables', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('qr_tables', 'restaurant_id')
    op.drop_constraint(None, 'qr_settings', type_='foreignkey')
    op.drop_index(op.f('ix_qr_settings_restaurant_id'), table_name='qr_settings')
    op.alter_column('qr_settings', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('qr_settings', 'restaurant_id')
    op.drop_constraint(None, 'qr_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_qr_sessions_restaurant_id'), table_name='qr_sessions')
    op.alter_column('qr_sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('qr_sessions', 'last_activity',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('qr_sessions', 'start_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('qr_sessions', 'restaurant_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_restaurant_id'), table_name='products')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.create_index('ix_products_slug', 'products', ['slug'], unique=True)
    op.alter_column('products', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('products', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('products', 'restaurant_id')
    op.drop_constraint(None, 'product_modifiers', type_='foreignkey')
    op.drop_index(op.f('ix_product_modifiers_restaurant_id'), table_name='product_modifiers')
    op.alter_column('product_modifiers', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('product_modifiers', 'restaurant_id')
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_restaurant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.create_index('ix_orders_order_number', 'orders', ['order_number'], unique=True)
    op.alter_column('orders', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('orders', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('orders', 'restaurant_id')
    op.drop_constraint(None, 'order_taxes', type_='foreignkey')
    op.drop_index(op.f('ix_order_taxes_restaurant_id'), table_name='order_taxes')
    op.alter_column('order_taxes', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('order_taxes', 'restaurant_id')
    op.drop_constraint(None, 'order_status_history', type_='foreignkey')
    op.drop_index(op.f('ix_order_status_history_restaurant_id'), table_name='order_status_history')
    op.alter_column('order_status_history', 'timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('order_status_history', 'restaurant_id')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_index(op.f('ix_order_items_restaurant_id'), table_name='order_items')
    op.alter_column('order_items', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('order_items', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('order_items', 'restaurant_id')
    op.drop_constraint(None, 'order_item_modifiers', type_='foreignkey')
    op.drop_index(op.f('ix_order_item_modifiers_restaurant_id'), table_name='order_item_modifiers')
    op.alter_column('order_item_modifiers', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('order_item_modifiers', 'restaurant_id')
    op.drop_constraint(None, 'modifiers', type_='foreignkey')
    op.drop_index(op.f('ix_modifiers_restaurant_id'), table_name='modifiers')
    op.alter_column('modifiers', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('modifiers', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('modifiers', 'restaurant_id')
    op.drop_constraint(None, 'modifier_options', type_='foreignkey')
    op.drop_index(op.f('ix_modifier_options_restaurant_id'), table_name='modifier_options')
    op.alter_column('modifier_options', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('modifier_options', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('modifier_options', 'restaurant_id')
    op.drop_constraint(None, 'loyalty_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_loyalty_transactions_restaurant_id'), table_name='loyalty_transactions')
    op.alter_column('loyalty_transactions', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('loyalty_transactions', 'restaurant_id')
    op.drop_constraint(None, 'loyalty_rules', type_='foreignkey')
    op.drop_index(op.f('ix_loyalty_rules_restaurant_id'), table_name='loyalty_rules')
    op.alter_column('loyalty_rules', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('loyalty_rules', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('loyalty_rules', 'restaurant_id')
    op.drop_constraint(None, 'kot_groups', type_='foreignkey')
    op.drop_index(op.f('ix_kot_groups_restaurant_id'), table_name='kot_groups')
    op.alter_column('kot_groups', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('kot_groups', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('kot_groups', 'restaurant_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_restaurant_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.create_index('ix_customers_phone', 'customers', ['phone'], unique=True)
    op.create_index('email', 'customers', ['email'], unique=True)
    op.alter_column('customers', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('customers', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('customers', 'restaurant_id')
    op.drop_constraint(None, 'customer_tags', type_='foreignkey')
    op.drop_index(op.f('ix_customer_tags_restaurant_id'), table_name='customer_tags')
    op.drop_index(op.f('ix_customer_tags_name'), table_name='customer_tags')
    op.create_index('ix_customer_tags_name', 'customer_tags', ['name'], unique=True)
    op.alter_column('customer_tags', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('customer_tags', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('customer_tags', 'restaurant_id')
    op.drop_constraint(None, 'customer_tag_mapping', type_='foreignkey')
    op.drop_index(op.f('ix_customer_tag_mapping_restaurant_id'), table_name='customer_tag_mapping')
    op.alter_column('customer_tag_mapping', 'assigned_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('customer_tag_mapping', 'restaurant_id')
    op.drop_constraint(None, 'combo_products', type_='foreignkey')
    op.drop_index(op.f('ix_combo_products_restaurant_id'), table_name='combo_products')
    op.drop_index(op.f('ix_combo_products_slug'), table_name='combo_products')
    op.create_index('ix_combo_products_slug', 'combo_products', ['slug'], unique=True)
    op.alter_column('combo_products', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('combo_products', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('combo_products', 'restaurant_id')
    op.drop_constraint(None, 'combo_items', type_='foreignkey')
    op.drop_index(op.f('ix_combo_items_restaurant_id'), table_name='combo_items')
    op.alter_column('combo_items', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('combo_items', 'restaurant_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_index(op.f('ix_categories_restaurant_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.create_index('ix_categories_slug', 'categories', ['slug'], unique=True)
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_index('ix_categories_name', 'categories', ['name'], unique=True)
    op.alter_column('categories', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('categories', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('categories', 'restaurant_id')
    op.create_table('translations',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('entity_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='Type of entity: product, category, modifier, etc.'),
    sa.Column('entity_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='ID of the entity being translated'),
    sa.Column('field_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='Field being translated: name, description, etc.'),
    sa.Column('language_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=5), nullable=False, comment='Language code: en, es, fr, ar'),
    sa.Column('translation_value', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000), nullable=False, comment='Translated text'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Stores translations for all entities',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='Stores translations for all entities',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_unique_translation', 'translations', ['entity_type', 'entity_id', 'field_name', 'language_code'], unique=True)
    op.create_index('idx_language', 'translations', ['language_code'], unique=False)
    op.create_index('idx_entity_lookup', 'translations', ['entity_type', 'entity_id'], unique=False)
    op.drop_index(op.f('ix_invoices_subscription_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_restaurant_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_restaurant_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_payment_gateway_subscription_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_restaurant_owners_user_id'), table_name='restaurant_owners')
    op.drop_index(op.f('ix_restaurant_owners_restaurant_id'), table_name='restaurant_owners')
    op.drop_table('restaurant_owners')
    op.drop_index(op.f('ix_restaurant_invitations_token'), table_name='restaurant_invitations')
    op.drop_index(op.f('ix_restaurant_invitations_restaurant_id'), table_name='restaurant_invitations')
    op.drop_index(op.f('ix_restaurant_invitations_email'), table_name='restaurant_invitations')
    op.drop_table('restaurant_invitations')
    op.drop_index(op.f('ix_platform_admins_user_id'), table_name='platform_admins')
    op.drop_table('platform_admins')
    op.drop_index(op.f('ix_subscription_plans_name'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_restaurants_subscription_status'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_subscription_plan'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_slug'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_name'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_is_active'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_email'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_created_at'), table_name='restaurants')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
