"""Add comprehensive category fields

Revision ID: 0fa7409c428d
Revises: 481bac3739a4
Create Date: 2025-12-31 13:43:16.779125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fa7409c428d'
down_revision: Union[str, None] = '481bac3739a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('parent_id', sa.String(length=36), nullable=True))
    op.add_column('categories', sa.Column('level', sa.Integer(), nullable=False))
    op.add_column('categories', sa.Column('is_featured', sa.Boolean(), nullable=False))
    op.add_column('categories', sa.Column('icon', sa.String(length=500), nullable=True))
    op.add_column('categories', sa.Column('banner_image', sa.String(length=500), nullable=True))
    op.add_column('categories', sa.Column('thumbnail', sa.String(length=500), nullable=True))
    op.add_column('categories', sa.Column('color', sa.String(length=7), nullable=True))
    op.add_column('categories', sa.Column('background_color', sa.String(length=7), nullable=True))
    op.add_column('categories', sa.Column('text_color', sa.String(length=7), nullable=True))
    op.add_column('categories', sa.Column('display_type', sa.String(length=20), nullable=True))
    op.add_column('categories', sa.Column('items_per_row', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('show_in_menu', sa.Boolean(), nullable=False))
    op.add_column('categories', sa.Column('show_in_homepage', sa.Boolean(), nullable=False))
    op.add_column('categories', sa.Column('show_in_pos', sa.Boolean(), nullable=False))
    op.add_column('categories', sa.Column('available_for_delivery', sa.Boolean(), nullable=False))
    op.add_column('categories', sa.Column('available_for_takeaway', sa.Boolean(), nullable=False))
    op.add_column('categories', sa.Column('available_for_dine_in', sa.Boolean(), nullable=False))
    op.add_column('categories', sa.Column('available_from_time', sa.String(length=10), nullable=True))
    op.add_column('categories', sa.Column('available_to_time', sa.String(length=10), nullable=True))
    op.add_column('categories', sa.Column('available_days', sa.JSON(), nullable=True))
    op.add_column('categories', sa.Column('tax_rate', sa.Float(), nullable=True))
    op.add_column('categories', sa.Column('tax_inclusive', sa.Boolean(), nullable=False))
    op.add_column('categories', sa.Column('seo_title', sa.String(length=200), nullable=True))
    op.add_column('categories', sa.Column('seo_description', sa.Text(), nullable=True))
    op.add_column('categories', sa.Column('seo_keywords', sa.Text(), nullable=True))
    op.add_column('categories', sa.Column('meta_tags', sa.JSON(), nullable=True))
    op.add_column('categories', sa.Column('product_count', sa.Integer(), nullable=False))
    op.add_column('categories', sa.Column('total_sales', sa.Integer(), nullable=False))
    op.add_column('categories', sa.Column('view_count', sa.Integer(), nullable=False))
    op.add_column('categories', sa.Column('order_count', sa.Integer(), nullable=False))
    op.add_column('categories', sa.Column('commission_percentage', sa.Float(), nullable=True))
    op.add_column('categories', sa.Column('min_price', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('max_price', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('discount_applicable', sa.Boolean(), nullable=False))
    op.add_column('categories', sa.Column('default_discount_percentage', sa.Float(), nullable=True))
    op.add_column('categories', sa.Column('attributes', sa.JSON(), nullable=True))
    op.add_column('categories', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('categories', sa.Column('dietary_info', sa.JSON(), nullable=True))
    op.add_column('categories', sa.Column('kitchen_station', sa.String(length=50), nullable=True))
    op.add_column('categories', sa.Column('preparation_area', sa.String(length=50), nullable=True))
    op.add_column('categories', sa.Column('avg_preparation_time', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('long_description', sa.Text(), nullable=True))
    op.add_column('categories', sa.Column('short_description', sa.String(length=500), nullable=True))
    op.add_column('categories', sa.Column('ingredients_note', sa.Text(), nullable=True))
    op.add_column('categories', sa.Column('allergen_info', sa.Text(), nullable=True))
    op.add_column('categories', sa.Column('external_id', sa.String(length=100), nullable=True))
    op.add_column('categories', sa.Column('external_url', sa.String(length=500), nullable=True))
    op.add_column('categories', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_column('categories', 'deleted_at')
    op.drop_column('categories', 'external_url')
    op.drop_column('categories', 'external_id')
    op.drop_column('categories', 'allergen_info')
    op.drop_column('categories', 'ingredients_note')
    op.drop_column('categories', 'short_description')
    op.drop_column('categories', 'long_description')
    op.drop_column('categories', 'avg_preparation_time')
    op.drop_column('categories', 'preparation_area')
    op.drop_column('categories', 'kitchen_station')
    op.drop_column('categories', 'dietary_info')
    op.drop_column('categories', 'tags')
    op.drop_column('categories', 'attributes')
    op.drop_column('categories', 'default_discount_percentage')
    op.drop_column('categories', 'discount_applicable')
    op.drop_column('categories', 'max_price')
    op.drop_column('categories', 'min_price')
    op.drop_column('categories', 'commission_percentage')
    op.drop_column('categories', 'order_count')
    op.drop_column('categories', 'view_count')
    op.drop_column('categories', 'total_sales')
    op.drop_column('categories', 'product_count')
    op.drop_column('categories', 'meta_tags')
    op.drop_column('categories', 'seo_keywords')
    op.drop_column('categories', 'seo_description')
    op.drop_column('categories', 'seo_title')
    op.drop_column('categories', 'tax_inclusive')
    op.drop_column('categories', 'tax_rate')
    op.drop_column('categories', 'available_days')
    op.drop_column('categories', 'available_to_time')
    op.drop_column('categories', 'available_from_time')
    op.drop_column('categories', 'available_for_dine_in')
    op.drop_column('categories', 'available_for_takeaway')
    op.drop_column('categories', 'available_for_delivery')
    op.drop_column('categories', 'show_in_pos')
    op.drop_column('categories', 'show_in_homepage')
    op.drop_column('categories', 'show_in_menu')
    op.drop_column('categories', 'items_per_row')
    op.drop_column('categories', 'display_type')
    op.drop_column('categories', 'text_color')
    op.drop_column('categories', 'background_color')
    op.drop_column('categories', 'color')
    op.drop_column('categories', 'thumbnail')
    op.drop_column('categories', 'banner_image')
    op.drop_column('categories', 'icon')
    op.drop_column('categories', 'is_featured')
    op.drop_column('categories', 'level')
    op.drop_column('categories', 'parent_id')
    # ### end Alembic commands ###
