"""Add comprehensive restaurant settings fields

Revision ID: 481bac3739a4
Revises: d17263d5c022
Create Date: 2025-12-31 13:02:14.570050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '481bac3739a4'
down_revision: Union[str, None] = 'd17263d5c022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('vat_rate', sa.Float(), nullable=True))
    op.add_column('restaurants', sa.Column('sales_tax_rate', sa.Float(), nullable=True))
    op.add_column('restaurants', sa.Column('tax_number', sa.String(length=50), nullable=True))
    op.add_column('restaurants', sa.Column('opening_time', sa.String(length=10), nullable=True))
    op.add_column('restaurants', sa.Column('closing_time', sa.String(length=10), nullable=True))
    op.add_column('restaurants', sa.Column('is_24_hours', sa.Boolean(), nullable=False))
    op.add_column('restaurants', sa.Column('operating_days', sa.JSON(), nullable=True))
    op.add_column('restaurants', sa.Column('holiday_mode', sa.Boolean(), nullable=False))
    op.add_column('restaurants', sa.Column('special_hours', sa.JSON(), nullable=True))
    op.add_column('restaurants', sa.Column('payment_methods_allowed', sa.JSON(), nullable=True))
    op.add_column('restaurants', sa.Column('cash_enabled', sa.Boolean(), nullable=False))
    op.add_column('restaurants', sa.Column('card_enabled', sa.Boolean(), nullable=False))
    op.add_column('restaurants', sa.Column('upi_enabled', sa.Boolean(), nullable=False))
    op.add_column('restaurants', sa.Column('wallet_enabled', sa.Boolean(), nullable=False))
    op.add_column('restaurants', sa.Column('online_payment_enabled', sa.Boolean(), nullable=False))
    op.add_column('restaurants', sa.Column('payment_gateway', sa.String(length=50), nullable=True))
    op.add_column('restaurants', sa.Column('payment_gateway_key', sa.String(length=500), nullable=True))
    op.add_column('restaurants', sa.Column('payment_gateway_secret', sa.String(length=500), nullable=True))
    op.add_column('restaurants', sa.Column('enable_online_ordering', sa.Boolean(), nullable=False))
    op.add_column('restaurants', sa.Column('enable_table_booking', sa.Boolean(), nullable=False))
    op.add_column('restaurants', sa.Column('enable_delivery', sa.Boolean(), nullable=False))
    op.add_column('restaurants', sa.Column('enable_takeaway', sa.Boolean(), nullable=False))
    op.add_column('restaurants', sa.Column('enable_dine_in', sa.Boolean(), nullable=False))
    op.add_column('restaurants', sa.Column('delivery_radius', sa.Float(), nullable=True))
    op.add_column('restaurants', sa.Column('delivery_charge', sa.Float(), nullable=True))
    op.add_column('restaurants', sa.Column('minimum_order_value', sa.Float(), nullable=True))
    op.add_column('restaurants', sa.Column('free_delivery_above', sa.Float(), nullable=True))
    op.add_column('restaurants', sa.Column('total_tables', sa.Integer(), nullable=True))
    op.add_column('restaurants', sa.Column('total_seats', sa.Integer(), nullable=True))
    op.add_column('restaurants', sa.Column('max_party_size', sa.Integer(), nullable=True))
    op.add_column('restaurants', sa.Column('enable_email_notifications', sa.Boolean(), nullable=False))
    op.add_column('restaurants', sa.Column('enable_sms_notifications', sa.Boolean(), nullable=False))
    op.add_column('restaurants', sa.Column('enable_push_notifications', sa.Boolean(), nullable=False))
    op.add_column('restaurants', sa.Column('notification_email', sa.String(length=255), nullable=True))
    op.add_column('restaurants', sa.Column('notification_phone', sa.String(length=20), nullable=True))
    op.add_column('restaurants', sa.Column('receipt_header', sa.Text(), nullable=True))
    op.add_column('restaurants', sa.Column('receipt_footer', sa.Text(), nullable=True))
    op.add_column('restaurants', sa.Column('invoice_prefix', sa.String(length=10), nullable=True))
    op.add_column('restaurants', sa.Column('invoice_counter', sa.Integer(), nullable=False))
    op.add_column('restaurants', sa.Column('enable_auto_print', sa.Boolean(), nullable=False))
    op.add_column('restaurants', sa.Column('website_url', sa.String(length=500), nullable=True))
    op.add_column('restaurants', sa.Column('facebook_url', sa.String(length=500), nullable=True))
    op.add_column('restaurants', sa.Column('instagram_url', sa.String(length=500), nullable=True))
    op.add_column('restaurants', sa.Column('twitter_url', sa.String(length=500), nullable=True))
    op.add_column('restaurants', sa.Column('allow_tips', sa.Boolean(), nullable=False))
    op.add_column('restaurants', sa.Column('default_tip_percentage', sa.Float(), nullable=True))
    op.add_column('restaurants', sa.Column('enable_loyalty_program', sa.Boolean(), nullable=False))
    op.add_column('restaurants', sa.Column('loyalty_points_per_currency', sa.Float(), nullable=True))
    op.add_column('restaurants', sa.Column('enable_kot', sa.Boolean(), nullable=False))
    op.add_column('restaurants', sa.Column('enable_kds', sa.Boolean(), nullable=False))
    op.add_column('restaurants', sa.Column('auto_accept_orders', sa.Boolean(), nullable=False))
    op.add_column('restaurants', sa.Column('preparation_time_buffer', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'preparation_time_buffer')
    op.drop_column('restaurants', 'auto_accept_orders')
    op.drop_column('restaurants', 'enable_kds')
    op.drop_column('restaurants', 'enable_kot')
    op.drop_column('restaurants', 'loyalty_points_per_currency')
    op.drop_column('restaurants', 'enable_loyalty_program')
    op.drop_column('restaurants', 'default_tip_percentage')
    op.drop_column('restaurants', 'allow_tips')
    op.drop_column('restaurants', 'twitter_url')
    op.drop_column('restaurants', 'instagram_url')
    op.drop_column('restaurants', 'facebook_url')
    op.drop_column('restaurants', 'website_url')
    op.drop_column('restaurants', 'enable_auto_print')
    op.drop_column('restaurants', 'invoice_counter')
    op.drop_column('restaurants', 'invoice_prefix')
    op.drop_column('restaurants', 'receipt_footer')
    op.drop_column('restaurants', 'receipt_header')
    op.drop_column('restaurants', 'notification_phone')
    op.drop_column('restaurants', 'notification_email')
    op.drop_column('restaurants', 'enable_push_notifications')
    op.drop_column('restaurants', 'enable_sms_notifications')
    op.drop_column('restaurants', 'enable_email_notifications')
    op.drop_column('restaurants', 'max_party_size')
    op.drop_column('restaurants', 'total_seats')
    op.drop_column('restaurants', 'total_tables')
    op.drop_column('restaurants', 'free_delivery_above')
    op.drop_column('restaurants', 'minimum_order_value')
    op.drop_column('restaurants', 'delivery_charge')
    op.drop_column('restaurants', 'delivery_radius')
    op.drop_column('restaurants', 'enable_dine_in')
    op.drop_column('restaurants', 'enable_takeaway')
    op.drop_column('restaurants', 'enable_delivery')
    op.drop_column('restaurants', 'enable_table_booking')
    op.drop_column('restaurants', 'enable_online_ordering')
    op.drop_column('restaurants', 'payment_gateway_secret')
    op.drop_column('restaurants', 'payment_gateway_key')
    op.drop_column('restaurants', 'payment_gateway')
    op.drop_column('restaurants', 'online_payment_enabled')
    op.drop_column('restaurants', 'wallet_enabled')
    op.drop_column('restaurants', 'upi_enabled')
    op.drop_column('restaurants', 'card_enabled')
    op.drop_column('restaurants', 'cash_enabled')
    op.drop_column('restaurants', 'payment_methods_allowed')
    op.drop_column('restaurants', 'special_hours')
    op.drop_column('restaurants', 'holiday_mode')
    op.drop_column('restaurants', 'operating_days')
    op.drop_column('restaurants', 'is_24_hours')
    op.drop_column('restaurants', 'closing_time')
    op.drop_column('restaurants', 'opening_time')
    op.drop_column('restaurants', 'tax_number')
    op.drop_column('restaurants', 'sales_tax_rate')
    op.drop_column('restaurants', 'vat_rate')
    # ### end Alembic commands ###
