"""Add Modifier relationships

Revision ID: 4f41bbce5566
Revises: cb0f4438b485
Create Date: 2026-03-29 13:15:20.676765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f41bbce5566'
down_revision: Union[str, None] = 'cb0f4438b485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sales_reports_created_at'), 'sales_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_sales_reports_from_date'), 'sales_reports', ['from_date'], unique=False)
    op.create_index(op.f('ix_sales_reports_generated_by'), 'sales_reports', ['generated_by'], unique=False)
    op.create_index(op.f('ix_sales_reports_report_date'), 'sales_reports', ['report_date'], unique=False)
    op.create_index(op.f('ix_sales_reports_report_number'), 'sales_reports', ['report_number'], unique=True)
    op.create_index(op.f('ix_sales_reports_report_type'), 'sales_reports', ['report_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_reports_report_type'), table_name='sales_reports')
    op.drop_index(op.f('ix_sales_reports_report_number'), table_name='sales_reports')
    op.drop_index(op.f('ix_sales_reports_report_date'), table_name='sales_reports')
    op.drop_index(op.f('ix_sales_reports_generated_by'), table_name='sales_reports')
    op.drop_index(op.f('ix_sales_reports_from_date'), table_name='sales_reports')
    op.drop_index(op.f('ix_sales_reports_created_at'), table_name='sales_reports')
    # ### end Alembic commands ###
