"""initial_fresh_start

Revision ID: 6cb463976471
Revises: 
Create Date: 2025-12-18 17:54:32.229207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cb463976471'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('device_type', sa.String(length=100), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'FORGOT_PASSWORD', name='loginattemptstatus'), nullable=False),
    sa.Column('failure_reason', sa.Enum('INVALID_EMAIL', 'INVALID_PASSWORD', 'ACCOUNT_INACTIVE', 'ACCOUNT_LOCKED', 'NONE', name='loginattemptfailurereason'), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('operating_system', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_logs_attempted_at'), 'login_logs', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_login_logs_email'), 'login_logs', ['email'], unique=False)
    op.create_index(op.f('ix_login_logs_id'), 'login_logs', ['id'], unique=False)
    op.create_index(op.f('ix_login_logs_status'), 'login_logs', ['status'], unique=False)
    op.create_index(op.f('ix_login_logs_user_id'), 'login_logs', ['user_id'], unique=False)
    op.create_table('restaurants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('business_type', sa.Enum('CAFE', 'RESTAURANT', 'BAR', 'FOOD_TRUCK', 'BAKERY', 'CLOUD_KITCHEN', 'QUICK_SERVICE', 'FINE_DINING', name='businesstype'), nullable=True),
    sa.Column('cuisine_type', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('alternate_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.String(length=20), nullable=True),
    sa.Column('longitude', sa.String(length=20), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('fssai_license', sa.String(length=14), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('banner_image', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=False),
    sa.Column('accent_color', sa.String(length=7), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('time_format', sa.String(length=10), nullable=False),
    sa.Column('enable_gst', sa.Boolean(), nullable=False),
    sa.Column('cgst_rate', sa.Float(), nullable=True),
    sa.Column('sgst_rate', sa.Float(), nullable=True),
    sa.Column('igst_rate', sa.Float(), nullable=True),
    sa.Column('service_charge_percentage', sa.Float(), nullable=True),
    sa.Column('subscription_plan', sa.Enum('TRIAL', 'BASIC', 'PRO', 'ENTERPRISE', name='subscriptionplantype'), nullable=False),
    sa.Column('subscription_status', sa.Enum('ACTIVE', 'SUSPENDED', 'CANCELLED', 'EXPIRED', 'PAST_DUE', name='subscriptionstatus'), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_started_at', sa.DateTime(), nullable=True),
    sa.Column('billing_email', sa.String(length=255), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_products', sa.Integer(), nullable=False),
    sa.Column('max_orders_per_month', sa.Integer(), nullable=False),
    sa.Column('max_locations', sa.Integer(), nullable=False),
    sa.Column('current_users', sa.Integer(), nullable=False),
    sa.Column('current_products', sa.Integer(), nullable=False),
    sa.Column('current_orders_this_month', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('suspension_reason', sa.Text(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('onboarding_step', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurants_created_at'), 'restaurants', ['created_at'], unique=False)
    op.create_index(op.f('ix_restaurants_email'), 'restaurants', ['email'], unique=False)
    op.create_index(op.f('ix_restaurants_gstin'), 'restaurants', ['gstin'], unique=False)
    op.create_index(op.f('ix_restaurants_is_active'), 'restaurants', ['is_active'], unique=False)
    op.create_index(op.f('ix_restaurants_name'), 'restaurants', ['name'], unique=False)
    op.create_index(op.f('ix_restaurants_slug'), 'restaurants', ['slug'], unique=True)
    op.create_index(op.f('ix_restaurants_subscription_plan'), 'restaurants', ['subscription_plan'], unique=False)
    op.create_index(op.f('ix_restaurants_subscription_status'), 'restaurants', ['subscription_status'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tagline', sa.String(length=200), nullable=True),
    sa.Column('price_monthly', sa.Integer(), nullable=False),
    sa.Column('price_yearly', sa.Integer(), nullable=False),
    sa.Column('discount_yearly', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_products', sa.Integer(), nullable=False),
    sa.Column('max_orders_per_month', sa.Integer(), nullable=False),
    sa.Column('max_locations', sa.Integer(), nullable=False),
    sa.Column('max_storage_gb', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('badge', sa.String(length=50), nullable=True),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_name'), 'subscription_plans', ['name'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_active'), 'categories', ['active'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_index(op.f('ix_categories_restaurant_id'), 'categories', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=False)
    op.create_index(op.f('ix_categories_sort_order'), 'categories', ['sort_order'], unique=False)
    op.create_table('modifiers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('SINGLE', 'MULTIPLE', name='modifiertype'), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('min_selections', sa.Integer(), nullable=False),
    sa.Column('max_selections', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modifiers_category'), 'modifiers', ['category'], unique=False)
    op.create_index(op.f('ix_modifiers_restaurant_id'), 'modifiers', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_modifiers_type'), 'modifiers', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('restaurant_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_restaurant_id'), 'users', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('category_translations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_translations_category_id'), 'category_translations', ['category_id'], unique=False)
    op.create_index(op.f('ix_category_translations_language_code'), 'category_translations', ['language_code'], unique=False)
    op.create_table('combo_products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('max_quantity_per_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_combo_products_available'), 'combo_products', ['available'], unique=False)
    op.create_index(op.f('ix_combo_products_category_id'), 'combo_products', ['category_id'], unique=False)
    op.create_index(op.f('ix_combo_products_featured'), 'combo_products', ['featured'], unique=False)
    op.create_index(op.f('ix_combo_products_restaurant_id'), 'combo_products', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_combo_products_slug'), 'combo_products', ['slug'], unique=False)
    op.create_table('modifier_options',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('modifier_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['modifier_id'], ['modifiers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modifier_options_available'), 'modifier_options', ['available'], unique=False)
    op.create_index(op.f('ix_modifier_options_modifier_id'), 'modifier_options', ['modifier_id'], unique=False)
    op.create_index(op.f('ix_modifier_options_restaurant_id'), 'modifier_options', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_modifier_options_sort_order'), 'modifier_options', ['sort_order'], unique=False)
    op.create_table('modifier_translations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('modifier_id', sa.String(length=36), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['modifier_id'], ['modifiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modifier_translations_language_code'), 'modifier_translations', ['language_code'], unique=False)
    op.create_index(op.f('ix_modifier_translations_modifier_id'), 'modifier_translations', ['modifier_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('min_stock', sa.Integer(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('printer_tag', sa.String(length=50), nullable=True),
    sa.Column('preparation_time', sa.Integer(), nullable=False),
    sa.Column('nutritional_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_available'), 'products', ['available'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_department'), 'products', ['department'], unique=False)
    op.create_index(op.f('ix_products_featured'), 'products', ['featured'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_restaurant_id'), 'products', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=False)
    op.create_table('restaurant_invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_by', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_invitations_email'), 'restaurant_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_restaurant_invitations_restaurant_id'), 'restaurant_invitations', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_restaurant_invitations_token'), 'restaurant_invitations', ['token'], unique=True)
    op.create_table('restaurant_owners',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('invited_by', sa.String(length=36), nullable=True),
    sa.Column('invitation_accepted', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_owners_restaurant_id'), 'restaurant_owners', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_restaurant_owners_user_id'), 'restaurant_owners', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('plan', sa.Enum('TRIAL', 'BASIC', 'PRO', 'ENTERPRISE', name='subscriptionplantype'), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'CANCELLED', 'EXPIRED', 'PAST_DUE', name='subscriptionstatus'), nullable=False),
    sa.Column('price_per_month', sa.Integer(), nullable=False),
    sa.Column('price_per_year', sa.Integer(), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_gateway_customer_id', sa.String(length=255), nullable=True),
    sa.Column('payment_gateway_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('last_payment_date', sa.DateTime(), nullable=True),
    sa.Column('next_payment_date', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_by', sa.String(length=36), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_payment_gateway_subscription_id'), 'subscriptions', ['payment_gateway_subscription_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_plan'), 'subscriptions', ['plan'], unique=False)
    op.create_index(op.f('ix_subscriptions_restaurant_id'), 'subscriptions', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_table('combo_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('combo_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('choice_group', sa.String(length=50), nullable=True),
    sa.Column('choices', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['combo_id'], ['combo_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_combo_items_combo_id'), 'combo_items', ['combo_id'], unique=False)
    op.create_index(op.f('ix_combo_items_restaurant_id'), 'combo_items', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_combo_items_sort_order'), 'combo_items', ['sort_order'], unique=False)
    op.create_table('combo_product_translations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('combo_product_id', sa.String(length=36), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['combo_product_id'], ['combo_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_combo_product_translations_combo_product_id'), 'combo_product_translations', ['combo_product_id'], unique=False)
    op.create_index(op.f('ix_combo_product_translations_language_code'), 'combo_product_translations', ['language_code'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('previous_stock', sa.Integer(), nullable=False),
    sa.Column('new_stock', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Integer(), nullable=True),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_created_at'), 'inventory_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_product_id'), 'inventory_transactions', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_restaurant_id'), 'inventory_transactions', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_type'), 'inventory_transactions', ['type'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('tax', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('cgst_amount', sa.Integer(), nullable=True),
    sa.Column('sgst_amount', sa.Integer(), nullable=True),
    sa.Column('igst_amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', name='invoicestatus'), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_gateway_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('payment_gateway_charge_id', sa.String(length=255), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_restaurant_id'), 'invoices', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_invoices_subscription_id'), 'invoices', ['subscription_id'], unique=False)
    op.create_table('modifier_option_translations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('modifier_option_id', sa.String(length=36), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['modifier_option_id'], ['modifier_options.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modifier_option_translations_language_code'), 'modifier_option_translations', ['language_code'], unique=False)
    op.create_index(op.f('ix_modifier_option_translations_modifier_option_id'), 'modifier_option_translations', ['modifier_option_id'], unique=False)
    op.create_table('product_modifiers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('modifier_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['modifier_id'], ['modifiers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_modifiers_restaurant_id'), 'product_modifiers', ['restaurant_id'], unique=False)
    op.create_table('product_translations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_translations_language_code'), 'product_translations', ['language_code'], unique=False)
    op.create_index(op.f('ix_product_translations_product_id'), 'product_translations', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_translations_product_id'), table_name='product_translations')
    op.drop_index(op.f('ix_product_translations_language_code'), table_name='product_translations')
    op.drop_table('product_translations')
    op.drop_index(op.f('ix_product_modifiers_restaurant_id'), table_name='product_modifiers')
    op.drop_table('product_modifiers')
    op.drop_index(op.f('ix_modifier_option_translations_modifier_option_id'), table_name='modifier_option_translations')
    op.drop_index(op.f('ix_modifier_option_translations_language_code'), table_name='modifier_option_translations')
    op.drop_table('modifier_option_translations')
    op.drop_index(op.f('ix_invoices_subscription_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_restaurant_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_inventory_transactions_type'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_restaurant_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_product_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_created_at'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_combo_product_translations_language_code'), table_name='combo_product_translations')
    op.drop_index(op.f('ix_combo_product_translations_combo_product_id'), table_name='combo_product_translations')
    op.drop_table('combo_product_translations')
    op.drop_index(op.f('ix_combo_items_sort_order'), table_name='combo_items')
    op.drop_index(op.f('ix_combo_items_restaurant_id'), table_name='combo_items')
    op.drop_index(op.f('ix_combo_items_combo_id'), table_name='combo_items')
    op.drop_table('combo_items')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_restaurant_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_payment_gateway_subscription_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_restaurant_owners_user_id'), table_name='restaurant_owners')
    op.drop_index(op.f('ix_restaurant_owners_restaurant_id'), table_name='restaurant_owners')
    op.drop_table('restaurant_owners')
    op.drop_index(op.f('ix_restaurant_invitations_token'), table_name='restaurant_invitations')
    op.drop_index(op.f('ix_restaurant_invitations_restaurant_id'), table_name='restaurant_invitations')
    op.drop_index(op.f('ix_restaurant_invitations_email'), table_name='restaurant_invitations')
    op.drop_table('restaurant_invitations')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_restaurant_id'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_featured'), table_name='products')
    op.drop_index(op.f('ix_products_department'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_available'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_modifier_translations_modifier_id'), table_name='modifier_translations')
    op.drop_index(op.f('ix_modifier_translations_language_code'), table_name='modifier_translations')
    op.drop_table('modifier_translations')
    op.drop_index(op.f('ix_modifier_options_sort_order'), table_name='modifier_options')
    op.drop_index(op.f('ix_modifier_options_restaurant_id'), table_name='modifier_options')
    op.drop_index(op.f('ix_modifier_options_modifier_id'), table_name='modifier_options')
    op.drop_index(op.f('ix_modifier_options_available'), table_name='modifier_options')
    op.drop_table('modifier_options')
    op.drop_index(op.f('ix_combo_products_slug'), table_name='combo_products')
    op.drop_index(op.f('ix_combo_products_restaurant_id'), table_name='combo_products')
    op.drop_index(op.f('ix_combo_products_featured'), table_name='combo_products')
    op.drop_index(op.f('ix_combo_products_category_id'), table_name='combo_products')
    op.drop_index(op.f('ix_combo_products_available'), table_name='combo_products')
    op.drop_table('combo_products')
    op.drop_index(op.f('ix_category_translations_language_code'), table_name='category_translations')
    op.drop_index(op.f('ix_category_translations_category_id'), table_name='category_translations')
    op.drop_table('category_translations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_restaurant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_modifiers_type'), table_name='modifiers')
    op.drop_index(op.f('ix_modifiers_restaurant_id'), table_name='modifiers')
    op.drop_index(op.f('ix_modifiers_category'), table_name='modifiers')
    op.drop_table('modifiers')
    op.drop_index(op.f('ix_categories_sort_order'), table_name='categories')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_restaurant_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_active'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_subscription_plans_name'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_restaurants_subscription_status'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_subscription_plan'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_slug'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_name'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_is_active'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_gstin'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_email'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_created_at'), table_name='restaurants')
    op.drop_table('restaurants')
    op.drop_index(op.f('ix_login_logs_user_id'), table_name='login_logs')
    op.drop_index(op.f('ix_login_logs_status'), table_name='login_logs')
    op.drop_index(op.f('ix_login_logs_id'), table_name='login_logs')
    op.drop_index(op.f('ix_login_logs_email'), table_name='login_logs')
    op.drop_index(op.f('ix_login_logs_attempted_at'), table_name='login_logs')
    op.drop_table('login_logs')
    # ### end Alembic commands ###
