"""Add translation tables for multi-language support

Revision ID: 6ce724cadf8f
Revises: dc8898fdb4b1
Create Date: 2025-12-16 13:09:18.923508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ce724cadf8f'
down_revision: Union[str, None] = 'dc8898fdb4b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
