"""Add data import module with import tracking and templates

Revision ID: bf2c2e13f3c9
Revises: caff3b24ffed
Create Date: 2025-12-31 14:41:25.159272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf2c2e13f3c9'
down_revision: Union[str, None] = 'caff3b24ffed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
