"""Add reports module with sales, item-wise, category-wise reports and scheduling

Revision ID: caff3b24ffed
Revises: a2fc39ab9150
Create Date: 2025-12-31 14:24:56.413071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caff3b24ffed'
down_revision: Union[str, None] = 'a2fc39ab9150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
