"""add staff and role management tables

Revision ID: d17263d5c022
Revises: b365172101b7
Create Date: 2025-12-30 17:54:56.942207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17263d5c022'
down_revision: Union[str, None] = 'b365172101b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.Enum('ADMIN', 'MANAGER', 'CASHIER', 'CAPTAIN', 'KITCHEN_STAFF', 'WAITER', 'DELIVERY_BOY', name='userrole'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=False)
    op.create_index(op.f('ix_roles_is_active'), 'roles', ['is_active'], unique=False)
    op.create_index(op.f('ix_roles_restaurant_id'), 'roles', ['restaurant_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission', sa.Enum('CREATE_ORDER', 'VIEW_ORDER', 'UPDATE_ORDER', 'DELETE_ORDER', 'CANCEL_ORDER', 'REFUND_ORDER', 'CREATE_PRODUCT', 'VIEW_PRODUCT', 'UPDATE_PRODUCT', 'DELETE_PRODUCT', 'CREATE_INGREDIENT', 'VIEW_INGREDIENT', 'UPDATE_INGREDIENT', 'DELETE_INGREDIENT', 'CREATE_PURCHASE_ORDER', 'RECEIVE_PURCHASE_ORDER', 'CREATE_USER', 'VIEW_USER', 'UPDATE_USER', 'DELETE_USER', 'CREATE_STAFF', 'VIEW_STAFF', 'UPDATE_STAFF', 'DELETE_STAFF', 'APPROVE_LEAVE', 'CREATE_RESTAURANT', 'VIEW_RESTAURANT', 'UPDATE_RESTAURANT', 'DELETE_RESTAURANT', 'CREATE_TABLE', 'VIEW_TABLE', 'UPDATE_TABLE', 'DELETE_TABLE', 'VIEW_REPORTS', 'VIEW_SALES_REPORT', 'VIEW_INVENTORY_REPORT', 'VIEW_STAFF_REPORT', 'VIEW_FINANCIAL', 'MANAGE_PAYMENT', 'GIVE_DISCOUNT', 'VIEW_KOT', 'UPDATE_KOT_STATUS', 'MANAGE_SETTINGS', name='permissiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_permission'), 'role_permissions', ['permission'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('alternate_phone', sa.String(length=20), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_relation', sa.String(length=50), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=False),
    sa.Column('date_of_leaving', sa.Date(), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('basic_salary', sa.Integer(), nullable=True),
    sa.Column('allowances', sa.Integer(), nullable=True),
    sa.Column('total_salary', sa.Integer(), nullable=True),
    sa.Column('aadhar_number', sa.String(length=12), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('bank_account_number', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_ifsc_code', sa.String(length=11), nullable=True),
    sa.Column('default_shift_type', sa.Enum('MORNING', 'AFTERNOON', 'EVENING', 'NIGHT', 'FULL_DAY', name='shifttype'), nullable=True),
    sa.Column('working_days_per_week', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_on_leave', sa.Boolean(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_email'), 'staff', ['email'], unique=False)
    op.create_index(op.f('ix_staff_employee_code'), 'staff', ['employee_code'], unique=True)
    op.create_index(op.f('ix_staff_is_active'), 'staff', ['is_active'], unique=False)
    op.create_index(op.f('ix_staff_phone'), 'staff', ['phone'], unique=False)
    op.create_index(op.f('ix_staff_restaurant_id'), 'staff', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_staff_role_id'), 'staff', ['role_id'], unique=False)
    op.create_index(op.f('ix_staff_user_id'), 'staff', ['user_id'], unique=False)
    op.create_table('leave_applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('staff_id', sa.String(length=36), nullable=False),
    sa.Column('leave_type', sa.Enum('SICK_LEAVE', 'CASUAL_LEAVE', 'EARNED_LEAVE', 'MATERNITY_LEAVE', 'PATERNITY_LEAVE', 'UNPAID_LEAVE', name='leavetype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('is_half_day', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leavestatus'), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_applications_leave_type'), 'leave_applications', ['leave_type'], unique=False)
    op.create_index(op.f('ix_leave_applications_restaurant_id'), 'leave_applications', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_leave_applications_staff_id'), 'leave_applications', ['staff_id'], unique=False)
    op.create_index(op.f('ix_leave_applications_start_date'), 'leave_applications', ['start_date'], unique=False)
    op.create_index(op.f('ix_leave_applications_status'), 'leave_applications', ['status'], unique=False)
    op.create_table('leave_balances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('staff_id', sa.String(length=36), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.Enum('SICK_LEAVE', 'CASUAL_LEAVE', 'EARNED_LEAVE', 'MATERNITY_LEAVE', 'PATERNITY_LEAVE', 'UNPAID_LEAVE', name='leavetype'), nullable=False),
    sa.Column('total_allocated', sa.Integer(), nullable=True),
    sa.Column('used', sa.Integer(), nullable=True),
    sa.Column('remaining', sa.Integer(), nullable=True),
    sa.Column('carried_forward', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_balances_leave_type'), 'leave_balances', ['leave_type'], unique=False)
    op.create_index(op.f('ix_leave_balances_restaurant_id'), 'leave_balances', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_leave_balances_staff_id'), 'leave_balances', ['staff_id'], unique=False)
    op.create_index(op.f('ix_leave_balances_year'), 'leave_balances', ['year'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('staff_id', sa.String(length=36), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('shift_type', sa.Enum('MORNING', 'AFTERNOON', 'EVENING', 'NIGHT', 'FULL_DAY', name='shifttype'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('break_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_start_time', sa.DateTime(), nullable=True),
    sa.Column('actual_end_time', sa.DateTime(), nullable=True),
    sa.Column('is_assigned', sa.Boolean(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_restaurant_id'), 'shifts', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_shifts_shift_date'), 'shifts', ['shift_date'], unique=False)
    op.create_index(op.f('ix_shifts_staff_id'), 'shifts', ['staff_id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('staff_id', sa.String(length=36), nullable=False),
    sa.Column('shift_id', sa.String(length=36), nullable=True),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.Column('check_out_time', sa.DateTime(), nullable=True),
    sa.Column('total_hours_worked', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('overtime_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'HALF_DAY', 'LATE', 'ON_LEAVE', name='attendancestatus'), nullable=False),
    sa.Column('is_late', sa.Boolean(), nullable=True),
    sa.Column('late_by_minutes', sa.Integer(), nullable=True),
    sa.Column('check_in_location', sa.String(length=255), nullable=True),
    sa.Column('check_out_location', sa.String(length=255), nullable=True),
    sa.Column('check_in_ip', sa.String(length=50), nullable=True),
    sa.Column('check_out_ip', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_attendance_date'), 'attendance', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendance_restaurant_id'), 'attendance', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_attendance_shift_id'), 'attendance', ['shift_id'], unique=False)
    op.create_index(op.f('ix_attendance_staff_id'), 'attendance', ['staff_id'], unique=False)
    op.create_index(op.f('ix_attendance_status'), 'attendance', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_status'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_staff_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_shift_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_restaurant_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_attendance_date'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_shifts_staff_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_shift_date'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_restaurant_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_leave_balances_year'), table_name='leave_balances')
    op.drop_index(op.f('ix_leave_balances_staff_id'), table_name='leave_balances')
    op.drop_index(op.f('ix_leave_balances_restaurant_id'), table_name='leave_balances')
    op.drop_index(op.f('ix_leave_balances_leave_type'), table_name='leave_balances')
    op.drop_table('leave_balances')
    op.drop_index(op.f('ix_leave_applications_status'), table_name='leave_applications')
    op.drop_index(op.f('ix_leave_applications_start_date'), table_name='leave_applications')
    op.drop_index(op.f('ix_leave_applications_staff_id'), table_name='leave_applications')
    op.drop_index(op.f('ix_leave_applications_restaurant_id'), table_name='leave_applications')
    op.drop_index(op.f('ix_leave_applications_leave_type'), table_name='leave_applications')
    op.drop_table('leave_applications')
    op.drop_index(op.f('ix_staff_user_id'), table_name='staff')
    op.drop_index(op.f('ix_staff_role_id'), table_name='staff')
    op.drop_index(op.f('ix_staff_restaurant_id'), table_name='staff')
    op.drop_index(op.f('ix_staff_phone'), table_name='staff')
    op.drop_index(op.f('ix_staff_is_active'), table_name='staff')
    op.drop_index(op.f('ix_staff_employee_code'), table_name='staff')
    op.drop_index(op.f('ix_staff_email'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_roles_restaurant_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_is_active'), table_name='roles')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
