"""Add product catalog and inventory tables

Revision ID: dc8898fdb4b1
Revises: 2d3893327675
Create Date: 2025-12-16 12:19:49.330606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc8898fdb4b1'
down_revision: Union[str, None] = '2d3893327675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
