"""add receipt_printers table

Revision ID: f1de57c350cd
Revises: a3b4c5d6e7f8
Create Date: 2026-09-23 02:46:33.733625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f1de57c350cd'
down_revision: Union[str, None] = 'a3b4c5d6e7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt_printers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.Enum('BILL', 'KOT', name='printerpurpose', native_enum=False, length=20), nullable=False),
    sa.Column('printer_name', sa.String(length=100), nullable=False),
    sa.Column('printer_url', sa.String(length=500), nullable=False),
    sa.Column('printer_token', sa.String(length=255), nullable=False),
    sa.Column('paper_size', sa.String(length=10), nullable=False),
    sa.Column('auto_print', sa.Boolean(), nullable=False),
    sa.Column('print_copies', sa.Integer(), nullable=False),
    sa.Column('logo_on_receipt', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'purpose', name='uq_receipt_printers_restaurant_purpose')
    )
    op.create_index(op.f('ix_receipt_printers_is_active'), 'receipt_printers', ['is_active'], unique=False)
    op.create_index(op.f('ix_receipt_printers_purpose'), 'receipt_printers', ['purpose'], unique=False)
    op.create_index(op.f('ix_receipt_printers_restaurant_id'), 'receipt_printers', ['restaurant_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected unrelated pre-existing drift between the
    # live DB and current models (dropping customer_email_otps, index changes
    # on cart_items/customers/table_transfers). That drift is out of scope for
    # this migration and was intentionally left out - it is not caused by the
    # receipt_printers addition and must not be applied here.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipt_printers_restaurant_id'), table_name='receipt_printers')
    op.drop_index(op.f('ix_receipt_printers_purpose'), table_name='receipt_printers')
    op.drop_index(op.f('ix_receipt_printers_is_active'), table_name='receipt_printers')
    op.drop_table('receipt_printers')
    # ### end Alembic commands ###
