"""add kitchen display system tables

Revision ID: ff8fb6adcc49
Revises: f9f4e05a2121
Create Date: 2025-12-30 17:06:07.480904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff8fb6adcc49'
down_revision: Union[str, None] = 'f9f4e05a2121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kitchen_stations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('station_type', sa.Enum('MAIN_KITCHEN', 'GRILL', 'FRYER', 'SALAD', 'BAR', 'DESSERT', 'BAKERY', 'PIZZA', 'SUSHI', 'WOK', 'EXPEDITOR', name='stationtype', native_enum=False, length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('floor', sa.String(length=50), nullable=True),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('color_code', sa.String(length=7), nullable=True),
    sa.Column('departments', sa.JSON(), nullable=True),
    sa.Column('printer_tags', sa.JSON(), nullable=True),
    sa.Column('max_concurrent_orders', sa.Integer(), nullable=True),
    sa.Column('average_prep_time', sa.Integer(), nullable=True),
    sa.Column('auto_accept_orders', sa.Boolean(), nullable=False),
    sa.Column('alert_on_new_order', sa.Boolean(), nullable=False),
    sa.Column('show_customer_names', sa.Boolean(), nullable=False),
    sa.Column('show_table_numbers', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('assigned_staff', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kitchen_stations_display_order'), 'kitchen_stations', ['display_order'], unique=False)
    op.create_index(op.f('ix_kitchen_stations_restaurant_id'), 'kitchen_stations', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_kitchen_stations_station_type'), 'kitchen_stations', ['station_type'], unique=False)
    op.create_table('kitchen_displays',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=36), nullable=False),
    sa.Column('station_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('table_number', sa.String(length=50), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'ACKNOWLEDGED', 'IN_PROGRESS', 'READY', 'COMPLETED', 'DELAYED', 'CANCELLED', name='displaystatus', native_enum=False, length=20), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ready_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('estimated_prep_time', sa.Integer(), nullable=True),
    sa.Column('actual_prep_time', sa.Integer(), nullable=True),
    sa.Column('due_time', sa.DateTime(), nullable=True),
    sa.Column('is_delayed', sa.Boolean(), nullable=False),
    sa.Column('is_rush', sa.Boolean(), nullable=False),
    sa.Column('alert_sent', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=36), nullable=True),
    sa.Column('prepared_by', sa.String(length=36), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('kitchen_notes', sa.Text(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('completed_items', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prepared_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['kitchen_stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kitchen_displays_due_time'), 'kitchen_displays', ['due_time'], unique=False)
    op.create_index(op.f('ix_kitchen_displays_order_id'), 'kitchen_displays', ['order_id'], unique=False)
    op.create_index(op.f('ix_kitchen_displays_order_number'), 'kitchen_displays', ['order_number'], unique=False)
    op.create_index(op.f('ix_kitchen_displays_priority'), 'kitchen_displays', ['priority'], unique=False)
    op.create_index(op.f('ix_kitchen_displays_restaurant_id'), 'kitchen_displays', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_kitchen_displays_station_id'), 'kitchen_displays', ['station_id'], unique=False)
    op.create_index(op.f('ix_kitchen_displays_status'), 'kitchen_displays', ['status'], unique=False)
    op.create_table('kitchen_display_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_id', sa.String(length=36), nullable=False),
    sa.Column('order_item_id', sa.String(length=36), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('modifiers', sa.JSON(), nullable=True),
    sa.Column('customization', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PREPARING', 'READY', 'SERVED', 'CANCELLED', 'ON_HOLD', name='itemstatus', native_enum=False, length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('prep_time', sa.Integer(), nullable=True),
    sa.Column('prepared_by', sa.String(length=36), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_complimentary', sa.Boolean(), nullable=False),
    sa.Column('requires_attention', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['display_id'], ['kitchen_displays.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prepared_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kitchen_display_items_display_id'), 'kitchen_display_items', ['display_id'], unique=False)
    op.create_index(op.f('ix_kitchen_display_items_order_item_id'), 'kitchen_display_items', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_kitchen_display_items_status'), 'kitchen_display_items', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kitchen_display_items_status'), table_name='kitchen_display_items')
    op.drop_index(op.f('ix_kitchen_display_items_order_item_id'), table_name='kitchen_display_items')
    op.drop_index(op.f('ix_kitchen_display_items_display_id'), table_name='kitchen_display_items')
    op.drop_table('kitchen_display_items')
    op.drop_index(op.f('ix_kitchen_displays_status'), table_name='kitchen_displays')
    op.drop_index(op.f('ix_kitchen_displays_station_id'), table_name='kitchen_displays')
    op.drop_index(op.f('ix_kitchen_displays_restaurant_id'), table_name='kitchen_displays')
    op.drop_index(op.f('ix_kitchen_displays_priority'), table_name='kitchen_displays')
    op.drop_index(op.f('ix_kitchen_displays_order_number'), table_name='kitchen_displays')
    op.drop_index(op.f('ix_kitchen_displays_order_id'), table_name='kitchen_displays')
    op.drop_index(op.f('ix_kitchen_displays_due_time'), table_name='kitchen_displays')
    op.drop_table('kitchen_displays')
    op.drop_index(op.f('ix_kitchen_stations_station_type'), table_name='kitchen_stations')
    op.drop_index(op.f('ix_kitchen_stations_restaurant_id'), table_name='kitchen_stations')
    op.drop_index(op.f('ix_kitchen_stations_display_order'), table_name='kitchen_stations')
    op.drop_table('kitchen_stations')
    # ### end Alembic commands ###
